//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewParticleArray.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int Id { get; set; }
        public int SequenceNo { get; set; }
        public string ProjectLink { get; set; }
        public string ImageTitle { get; set; }
        public string ImageLink { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectText { get; set; }
    }
}
